name: Deploy .NET 8 API to Azure App Service

on:
  push:
    branches:
      - main  # Deploy only when pushing to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore ./api

      - name: Build
        run: dotnet build --configuration Release --no-restore --project ./api

      - name: Publish
        run: dotnet publish -c Release -o ./publish ./api

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: weatherapp-backend  # Your Azure App Service name
          slot-name: production
          package: ./publish
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
