name: Push to Azure Repos

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  sync-to-azure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full commit history is fetched

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Add Azure Repos as remotes
        run: |
          git remote add azure1 https://mjwachira1:${{ secrets.AZURE_PAT }}@dev.azure.com/mjwachira1/WeatherApp/_git/WeatherApp
          git remote add azure2 https://SalesAppOrg:${{ secrets.AZURE_PAT2 }}@dev.azure.com/SalesAppOrg/WeatherApp/_git/WeatherApp
          git fetch azure1
          git fetch azure2

      - name: Push to both Azure Repos
        run: |
          git push --force azure1 main
          git push --force azure2 main
